service: schedule-cron-save-to-s3

custom:
  awsRegion: ${file(./serverless-config/env/env.${opt:stage}.yml):awsRegion}
  awsAccount: ${file(./serverless-config/env/env.${opt:stage}.yml):awsAccount}
  role: arn:aws:iam::${self:custom.awsAccount}:role/lambda-basic-execution

provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs10.x
  timeout: 60
  region: ${self:custom.awsRegion}
  versionFunctions: false
  role: ${self:custom.role}

functions:
  schedule-cron-save-to-s3:
    name: schedule-cron-save-to-s3-${opt:stage}
    description: Schedule cron save to s3
    handler: index.handler
    events:
      - schedule: rate(60 minutes)
    environment:
      BUCKET_NAME: ${file(./serverless-config/env/env.${opt:stage}.yml):environment.BUCKET_NAME}
